version: '3.9'
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - website_files:/var/www/html
      # - ./requirements/nginx/site.conf:/etc/nginx/conf/conf.d/site.conf
    networks:
      - inception_yourkesa
  wordpress:
    # image: wordpress:5.7.0-php8.0-fpm
    build: ./requirements/wordpress
    container_name: wordpress
    # depends_on:
    #   - mariadb
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    ports:
      - "9000:80"
    env_file:
      - .env
    volumes:
      - website_files:/var/www/html
    networks:
      - inception_yourkesa
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    # restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - inception_yourkesa
volumes:
  database:
  website_files:
networks:
  inception_yourkesa:
    driver: bridge
